# Generated by Django 6.0.4 on 2026-05-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_place_image_url_place_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='visit_time',
            field=models.TimeField(blank=True, help_text='방문/도착 시간', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='start_location',
            field=models.CharField(default='', help_text='출발지 (예: 인천 남동구)', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='theme',
            field=models.CharField(choices=[('couple', '👩\u200d❤️\u200d👨 커플 여행'), ('family', '👨\u200d👩\u200d👧\u200d👦 가족/부모님과'), ('solo', '🚶 나홀로 뚜벅이'), ('friends', '👯 친구와 함께'), ('drive', '🚗 드라이브/렌트카')], default='couple', help_text='테마 태그', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='travel_date',
            field=models.DateField(blank=True, help_text='참고용 여행 출발일', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='destination',
            field=models.CharField(help_text='목적지 (예: 강원도 강릉)', max_length=50),
        ),
    ]
