# Generated by Django 6.0.4 on 2026-05-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_place_visit_time_post_start_location_post_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='cost',
            field=models.IntegerField(default=0, help_text='이 장소에서 쓴 비용'),
        ),
        migrations.AlterField(
            model_name='post',
            name='total_time',
            field=models.CharField(default='0시간 0분', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='travel_date',
            field=models.DateField(blank=True, help_text='여행 시기', null=True),
        ),
    ]
