# Generated by Django 6.0.2 on 2026-05-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_place_cost_alter_post_total_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='start_location',
        ),
        migrations.AddField(
            model_name='post',
            name='start_district',
            field=models.CharField(default='', help_text='시/군/구', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='start_region',
            field=models.CharField(default='', help_text='시/도', max_length=20),
        ),
        migrations.AlterField(
            model_name='place',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='places/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='visit_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='destination',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='theme',
            field=models.CharField(choices=[('couple', '👩\u200d❤️\u200d👨 커플 여행'), ('family', '👨\u200d👩\u200d👧\u200d👦 가족/부모님과'), ('solo', '🚶 나홀로 뚜벅이'), ('friends', '👯 친구와 함께'), ('drive', '🚗 드라이브/렌트카')], default='couple', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='travel_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
