# Generated by Django 6.0.2 on 2026-05-04 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_start_location_post_start_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='start_neighborhood',
            field=models.CharField(default='', help_text='읍/면/동', max_length=20),
        ),
    ]
