# Generated by Django 6.0.2 on 2026-05-04 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_start_neighborhood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='travel_date',
            new_name='travel_end_date',
        ),
        migrations.RemoveField(
            model_name='place',
            name='visit_time',
        ),
        migrations.AddField(
            model_name='place',
            name='visit_time_str',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='travel_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_district',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_neighborhood',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_region',
            field=models.CharField(default='', max_length=20),
        ),
    ]
