# Generated by Django 6.0.2 on 2026-05-04 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_rename_travel_date_post_travel_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['day', 'id']},
        ),
        migrations.AddField(
            model_name='place',
            name='day',
            field=models.IntegerField(default=1),
        ),
    ]
