# Generated by Django 6.0.2 on 2026-05-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_place_latitude_place_longitude_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='start_time',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='post_thumbnails/'),
        ),
    ]
