# Generated by Django 6.0.2 on 2026-05-04 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_post_options_place_created_at_post_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_posts', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['day', 'id'], name='posts_place_day_b67575_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['place_name'], name='posts_place_place_n_8232b1_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='posts_post_created_183a3b_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['theme'], name='posts_post_theme_503ee6_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['start_region', 'start_district', 'start_neighborhood'], name='posts_post_start_r_d00271_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['views'], name='posts_post_views_df4da7_idx'),
        ),
    ]
