# Generated by Django 6.0.2 on 2026-05-04 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_post_author_alter_post_views_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_travel_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['post'], name='posts_postl_post_id_d568f5_idx'), models.Index(fields=['user'], name='posts_postl_user_id_8dc185_idx'), models.Index(fields=['ip_address'], name='posts_postl_ip_addr_42c0ec_idx'), models.Index(fields=['created_at'], name='posts_postl_created_f2d831_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('post', 'user'), name='unique_post_like_per_user'), models.UniqueConstraint(condition=models.Q(('ip_address__isnull', False), ('user__isnull', True)), fields=('post', 'ip_address'), name='unique_post_like_per_ip_guest')],
            },
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('viewed_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='posts.post')),
            ],
            options={
                'indexes': [models.Index(fields=['post', 'ip_address', 'viewed_on'], name='posts_postv_post_id_62003a_idx'), models.Index(fields=['viewed_on'], name='posts_postv_viewed__c0bf6f_idx')],
                'constraints': [models.UniqueConstraint(fields=('post', 'ip_address', 'viewed_on'), name='unique_post_view_per_ip_per_day')],
            },
        ),
    ]
