# Generated by Django 6.0.2 on 2026-05-04 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_postlike_postview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['day', 'id'], 'verbose_name': '방문 장소', 'verbose_name_plural': '방문 장소'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': '여행 루트', 'verbose_name_plural': '여행 루트'},
        ),
        migrations.AlterModelOptions(
            name='postlike',
            options={'verbose_name': '루트 추천', 'verbose_name_plural': '루트 추천'},
        ),
        migrations.AlterModelOptions(
            name='postview',
            options={'verbose_name': '루트 조회 기록', 'verbose_name_plural': '루트 조회 기록'},
        ),
        migrations.AddField(
            model_name='post',
            name='awarded_points',
            field=models.PositiveIntegerField(default=0, verbose_name='지급 포인트'),
        ),
        migrations.AddField(
            model_name='post',
            name='points_awarded',
            field=models.BooleanField(db_index=True, default=False, verbose_name='포인트 지급 여부'),
        ),
        migrations.AddField(
            model_name='post',
            name='review_note',
            field=models.TextField(blank=True, default='', help_text='수정 요청이나 반려 사유를 적어두는 관리자용 메모입니다.', verbose_name='검수 메모'),
        ),
        migrations.AddField(
            model_name='post',
            name='review_status',
            field=models.CharField(choices=[('pending', '검수중'), ('approved', '승인됨'), ('needs_edit', '수정요청'), ('rejected', '반려됨')], db_index=True, default='pending', max_length=20, verbose_name='검수 상태'),
        ),
        migrations.AddField(
            model_name='post',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='검수일'),
        ),
        migrations.AddField(
            model_name='post',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_travel_posts', to=settings.AUTH_USER_MODEL, verbose_name='검수자'),
        ),
        migrations.AlterField(
            model_name='place',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='경비'),
        ),
        migrations.AlterField(
            model_name='place',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='place',
            name='day',
            field=models.IntegerField(default=1, verbose_name='일차'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='places/', verbose_name='장소 이미지'),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='위도'),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='경도'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_name',
            field=models.CharField(max_length=100, verbose_name='장소명'),
        ),
        migrations.AlterField(
            model_name='place',
            name='visit_time_str',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='방문 시간'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='작성일'),
        ),
        migrations.AlterField(
            model_name='post',
            name='destination',
            field=models.CharField(max_length=50, verbose_name='대표 목적지'),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_district',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='출발 군/구'),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, verbose_name='출발지 위도'),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, verbose_name='출발지 경도'),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_neighborhood',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='출발 동/읍/면'),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_place_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='출발지 지도 위치'),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_region',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='출발 시/도'),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_time',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='출발 시간'),
        ),
        migrations.AlterField(
            model_name='post',
            name='theme',
            field=models.CharField(choices=[('couple', '👩\u200d❤️\u200d👨 커플 여행'), ('family', '👨\u200d👩\u200d👧\u200d👦 가족/부모님과'), ('solo', '🚶 나홀로 뚜벅이'), ('friends', '👯 친구와 함께'), ('drive', '🚗 드라이브/렌트카')], default='couple', max_length=20, verbose_name='여행 테마'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='post_thumbnails/', verbose_name='대표 이미지'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='루트 제목'),
        ),
        migrations.AlterField(
            model_name='post',
            name='total_cost',
            field=models.IntegerField(default=0, verbose_name='총 예상 경비'),
        ),
        migrations.AlterField(
            model_name='post',
            name='total_time',
            field=models.CharField(default='0시간 0분', max_length=50, verbose_name='총 예상 소요시간'),
        ),
        migrations.AlterField(
            model_name='post',
            name='travel_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='여행 종료일'),
        ),
        migrations.AlterField(
            model_name='post',
            name='travel_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='여행 시작일'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['review_status'], name='posts_post_review__b1c75a_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['points_awarded'], name='posts_post_points__3955f9_idx'),
        ),
    ]
