# Generated by Django 6.0.2 on 2026-05-04 22:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_alter_place_options_alter_post_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='review_notice_read',
            field=models.BooleanField(db_index=True, default=True, help_text='False이면 작성자 로그인 시 검수 결과 모달이 표시됩니다.', verbose_name='검수 결과 알림 확인 여부'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['review_notice_read'], name='posts_post_review__26a6f5_idx'),
        ),
    ]
