# Generated by Django 6.0.2 on 2026-05-05 04:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_post_review_notice_read_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='별점')),
                ('comment', models.TextField(blank=True, default='', verbose_name='리뷰 내용')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='노출 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='posts.post', verbose_name='여행 루트')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_reviews', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '루트 리뷰',
                'verbose_name_plural': '루트 리뷰',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['post', 'is_active'], name='posts_postr_post_id_ce2901_idx'), models.Index(fields=['user'], name='posts_postr_user_id_3f5e00_idx'), models.Index(fields=['rating'], name='posts_postr_rating_05ab94_idx'), models.Index(fields=['created_at'], name='posts_postr_created_a3e7b0_idx')],
                'constraints': [models.UniqueConstraint(fields=('post', 'user'), name='unique_route_review_per_user')],
            },
        ),
    ]
