# Generated by Django 6.0.2 on 2026-05-04 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
        ('posts', '0016_alter_place_options_alter_post_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointwallet',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='pointhistory',
            options={'ordering': ['-created_at'], 'verbose_name': '포인트 기록', 'verbose_name_plural': '포인트 기록'},
        ),
        migrations.RemoveField(
            model_name='pointhistory',
            name='point_type',
        ),
        migrations.AddField(
            model_name='pointhistory',
            name='balance_after',
            field=models.PositiveIntegerField(default=0, verbose_name='변동 후 잔액'),
        ),
        migrations.AddField(
            model_name='pointhistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_point_histories', to=settings.AUTH_USER_MODEL, verbose_name='처리자'),
        ),
        migrations.AddField(
            model_name='pointhistory',
            name='memo',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='메모'),
        ),
        migrations.AddField(
            model_name='pointhistory',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_histories', to='posts.post', verbose_name='관련 여행 루트'),
        ),
        migrations.AlterField(
            model_name='pointhistory',
            name='amount',
            field=models.IntegerField(help_text='지급은 양수, 차감은 음수로 기록됩니다.', verbose_name='포인트 변동'),
        ),
        migrations.AlterField(
            model_name='pointhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='pointhistory',
            name='reason',
            field=models.CharField(choices=[('route_approved', '루트 승인 보상'), ('route_bonus', '우수 루트 추가 보상'), ('shop_purchase', '포인트샵 사용'), ('admin_grant', '관리자 지급'), ('admin_deduct', '관리자 차감'), ('admin_adjust', '관리자 조정')], max_length=30, verbose_name='사유'),
        ),
        migrations.AlterField(
            model_name='pointhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_histories', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddIndex(
            model_name='pointhistory',
            index=models.Index(fields=['user', '-created_at'], name='points_poin_user_id_d9c297_idx'),
        ),
        migrations.AddIndex(
            model_name='pointhistory',
            index=models.Index(fields=['reason'], name='points_poin_reason_4719ea_idx'),
        ),
        migrations.AddIndex(
            model_name='pointhistory',
            index=models.Index(fields=['post'], name='points_poin_post_id_3cf77a_idx'),
        ),
        migrations.AddIndex(
            model_name='pointhistory',
            index=models.Index(fields=['created_at'], name='points_poin_created_ac6769_idx'),
        ),
        migrations.AddConstraint(
            model_name='pointhistory',
            constraint=models.UniqueConstraint(condition=models.Q(('post__isnull', False), ('reason', 'route_approved')), fields=('reason', 'post'), name='unique_points_route_approved_per_post'),
        ),
        migrations.DeleteModel(
            name='PointWallet',
        ),
    ]
