# Generated by Django 6.0.2 on 2026-05-05 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_remove_pointwallet_user_alter_pointhistory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdRewardCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('subtitle', models.CharField(blank=True, default='', max_length=120)),
                ('reward_points', models.PositiveIntegerField(default=30)),
                ('daily_limit', models.PositiveIntegerField(default=3)),
                ('emoji', models.CharField(default='📺', max_length=8)),
                ('ad_slot_key', models.CharField(blank=True, default='', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '광고 포인트 캠페인',
                'verbose_name_plural': '광고 포인트 캠페인',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AdRewardClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', '확인중'), ('approved', '지급완료'), ('rejected', '반려')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('user_notice_read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '광고 포인트 신청',
                'verbose_name_plural': '광고 포인트 신청',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('earn', '적립'), ('spend', '사용'), ('refund', '환불'), ('admin', '관리자 조정')], max_length=20)),
                ('reason', models.CharField(max_length=120)),
                ('memo', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '포인트 내역',
                'verbose_name_plural': '포인트 내역',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('culture', '문화상품권'), ('starbucks', '스타벅스'), ('cu', 'CU'), ('etc', '기타')], default='etc', max_length=30)),
                ('name', models.CharField(max_length=80)),
                ('brand', models.CharField(blank=True, default='', max_length=40)),
                ('face_value', models.PositiveIntegerField(default=0, help_text='실제 권면가 또는 예상 구매가')),
                ('required_points', models.PositiveIntegerField()),
                ('emoji', models.CharField(default='🎁', max_length=8)),
                ('description', models.CharField(blank=True, default='', max_length=180)),
                ('notice', models.TextField(blank=True, default='')),
                ('stock', models.PositiveIntegerField(default=0, help_text='0이면 품절')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '포인트샵 상품',
                'verbose_name_plural': '포인트샵 상품',
                'ordering': ['display_order', 'required_points', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spent', models.PositiveIntegerField()),
                ('recipient_email', models.EmailField(blank=True, default='', max_length=254)),
                ('status', models.CharField(choices=[('pending', '신청중'), ('approved', '승인완료'), ('sent', '발송완료'), ('rejected', '반려'), ('canceled', '취소')], default='pending', max_length=20)),
                ('coupon_code', models.TextField(blank=True, default='', help_text='쿠폰번호/PIN/발송 메모')),
                ('admin_note', models.TextField(blank=True, default='')),
                ('user_notice_read_at', models.DateTimeField(blank=True, null=True)),
                ('is_refunded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '쿠폰 교환 신청',
                'verbose_name_plural': '쿠폰 교환 신청',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='pointhistory',
            name='points_poin_user_id_d9c297_idx',
        ),
        migrations.RemoveIndex(
            model_name='pointhistory',
            name='points_poin_reason_4719ea_idx',
        ),
        migrations.RemoveIndex(
            model_name='pointhistory',
            name='points_poin_post_id_3cf77a_idx',
        ),
        migrations.RemoveIndex(
            model_name='pointhistory',
            name='points_poin_created_ac6769_idx',
        ),
        migrations.RemoveConstraint(
            model_name='pointhistory',
            name='unique_points_route_approved_per_post',
        ),
        migrations.AddField(
            model_name='adrewardclaim',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='points.adrewardcampaign'),
        ),
        migrations.AddField(
            model_name='adrewardclaim',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_reward_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='points.rewarditem'),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_redemptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PointHistory',
        ),
    ]
