# Generated by Django 6.0.2 on 2026-05-10 08:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='단일 IP 차단용. 예: 74.7.227.45', unique=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '차단 IP',
                'verbose_name_plural': '차단 IP',
                'indexes': [models.Index(fields=['is_active'], name='core_blocke_is_acti_ec5cf6_idx'), models.Index(fields=['created_at'], name='core_blocke_created_f44b14_idx')],
            },
        ),
        migrations.CreateModel(
            name='IPBlockRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidr', models.CharField(help_text='CIDR 대역 차단용. 예: 57.141.14.0/24', max_length=64, unique=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IP 대역 차단 규칙',
                'verbose_name_plural': 'IP 대역 차단 규칙',
                'indexes': [models.Index(fields=['is_active'], name='core_ipbloc_is_acti_f42464_idx'), models.Index(fields=['created_at'], name='core_ipbloc_created_cedb7b_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginAttemptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('path', models.TextField(blank=True, default='')),
                ('method', models.CharField(blank=True, default='GET', max_length=12)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('identifier', models.CharField(blank=True, default='', max_length=255)),
                ('success', models.BooleanField(blank=True, db_index=True, null=True)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('referer', models.TextField(blank=True, default='')),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempt_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '로그인 시도 로그',
                'verbose_name_plural': '로그인 시도 로그',
                'indexes': [models.Index(fields=['created_at'], name='core_logina_created_6c3bf9_idx'), models.Index(fields=['ip_address', 'created_at'], name='core_logina_ip_addr_cf0109_idx'), models.Index(fields=['success', 'created_at'], name='core_logina_success_b3b146_idx'), models.Index(fields=['status_code', 'created_at'], name='core_logina_status__4b9038_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('country', models.CharField(blank=True, default='Unknown', max_length=80)),
                ('method', models.CharField(blank=True, default='GET', max_length=12)),
                ('path', models.TextField()),
                ('query_string', models.TextField(blank=True, default='')),
                ('referer', models.TextField(blank=True, default='')),
                ('user_agent', models.TextField(blank=True, default='')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(choices=[('Human', 'Human'), ('Maybe Human', 'Maybe Human'), ('Bot', 'Bot'), ('Suspicious', 'Suspicious'), ('Blocked', 'Blocked')], db_index=True, default='Maybe Human', max_length=30)),
                ('is_bot', models.BooleanField(db_index=True, default=False)),
                ('is_suspicious', models.BooleanField(db_index=True, default=False)),
                ('is_blocked', models.BooleanField(db_index=True, default=False)),
                ('response_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pageview_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '페이지뷰 로그',
                'verbose_name_plural': '페이지뷰 로그',
                'indexes': [models.Index(fields=['created_at'], name='core_pagevi_created_4fd89e_idx'), models.Index(fields=['ip_address', 'created_at'], name='core_pagevi_ip_addr_489d38_idx'), models.Index(fields=['status_code', 'created_at'], name='core_pagevi_status__2d2aeb_idx'), models.Index(fields=['type', 'created_at'], name='core_pagevi_type_a2fd74_idx'), models.Index(fields=['is_blocked', 'created_at'], name='core_pagevi_is_bloc_3241e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('method', models.CharField(blank=True, default='GET', max_length=12)),
                ('path', models.TextField()),
                ('full_path', models.TextField(blank=True, default='')),
                ('referer', models.TextField(blank=True, default='')),
                ('user_agent', models.TextField(blank=True, default='')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(choices=[('Human', 'Human'), ('Maybe Human', 'Maybe Human'), ('Bot', 'Bot'), ('Suspicious', 'Suspicious'), ('Blocked', 'Blocked')], db_index=True, default='Maybe Human', max_length=30)),
                ('is_bot', models.BooleanField(db_index=True, default=False)),
                ('is_suspicious', models.BooleanField(db_index=True, default=False)),
                ('is_blocked', models.BooleanField(db_index=True, default=False)),
                ('response_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '요청 로그',
                'verbose_name_plural': '요청 로그',
                'indexes': [models.Index(fields=['created_at'], name='core_reques_created_96effa_idx'), models.Index(fields=['ip_address', 'created_at'], name='core_reques_ip_addr_fc366e_idx'), models.Index(fields=['status_code', 'created_at'], name='core_reques_status__0f464c_idx'), models.Index(fields=['is_bot', 'created_at'], name='core_reques_is_bot_17e3da_idx'), models.Index(fields=['is_blocked', 'created_at'], name='core_reques_is_bloc_637cd8_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('severity', models.CharField(choices=[('INFO', 'INFO'), ('WARNING', 'WARNING'), ('DANGER', 'DANGER'), ('CRITICAL', 'CRITICAL')], db_index=True, default='INFO', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('method', models.CharField(blank=True, default='GET', max_length=12)),
                ('path', models.TextField(blank=True, default='')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('referer', models.TextField(blank=True, default='')),
                ('message', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '보안 이벤트',
                'verbose_name_plural': '보안 이벤트',
                'indexes': [models.Index(fields=['created_at'], name='core_securi_created_dd270d_idx'), models.Index(fields=['event_type', 'created_at'], name='core_securi_event_t_e93b36_idx'), models.Index(fields=['severity', 'created_at'], name='core_securi_severit_a97267_idx'), models.Index(fields=['ip_address', 'created_at'], name='core_securi_ip_addr_183a8e_idx')],
            },
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('country', models.CharField(blank=True, default='Unknown', max_length=80)),
                ('type', models.CharField(choices=[('Human', 'Human'), ('Maybe Human', 'Maybe Human'), ('Bot', 'Bot'), ('Suspicious', 'Suspicious'), ('Blocked', 'Blocked')], db_index=True, default='Maybe Human', max_length=30)),
                ('path', models.TextField(blank=True, default='')),
                ('method', models.CharField(blank=True, default='GET', max_length=12)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('referer', models.TextField(blank=True, default='')),
                ('request_count', models.PositiveIntegerField(default=1)),
                ('is_bot', models.BooleanField(db_index=True, default=False)),
                ('is_blocked', models.BooleanField(db_index=True, default=False)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '방문자 로그',
                'verbose_name_plural': '방문자 로그',
                'indexes': [models.Index(fields=['visit_date', 'ip_address'], name='core_visito_visit_d_4564c4_idx'), models.Index(fields=['type', 'visit_date'], name='core_visito_type_f01e3e_idx'), models.Index(fields=['is_bot', 'visit_date'], name='core_visito_is_bot_8088f0_idx'), models.Index(fields=['is_blocked', 'visit_date'], name='core_visito_is_bloc_5eb17c_idx')],
                'unique_together': {('visit_date', 'ip_address')},
            },
        ),
    ]
