# Generated by Django 6.0.2 on 2026-05-04 23:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('free', '자유게시판'), ('question', '여행 질문'), ('tip', '여행 꿀팁'), ('companion', '동행 구하기'), ('notice', '공지사항')], default='free', max_length=20, verbose_name='카테고리')),
                ('title', models.CharField(max_length=120, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('image', models.ImageField(blank=True, null=True, upload_to='community/%Y/%m/', verbose_name='이미지')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('is_notice', models.BooleanField(default=False, verbose_name='공지 고정')),
                ('is_active', models.BooleanField(default=True, verbose_name='노출 여부')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '커뮤니티 글',
                'verbose_name_plural': '커뮤니티 글',
                'ordering': ['-is_notice', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='댓글 내용')),
                ('is_active', models.BooleanField(default=True, verbose_name='노출 여부')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.communitypost', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '커뮤니티 댓글',
                'verbose_name_plural': '커뮤니티 댓글',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['category', '-created_at'], name='community_c_categor_c6128e_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['is_notice', '-created_at'], name='community_c_is_noti_146952_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['is_active', '-created_at'], name='community_c_is_acti_d2c48f_idx'),
        ),
        migrations.AddIndex(
            model_name='communitycomment',
            index=models.Index(fields=['post', 'is_active', 'created_at'], name='community_c_post_id_e67623_idx'),
        ),
    ]
