# Generated by Django 6.0.2 on 2026-05-04 23:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='좋아요 유지')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='처음 누른 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '커뮤니티 좋아요',
                'verbose_name_plural': '커뮤니티 좋아요',
            },
        ),
        migrations.CreateModel(
            name='CommunityPostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP 주소')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='조회일')),
            ],
            options={
                'verbose_name': '커뮤니티 조회 기록',
                'verbose_name_plural': '커뮤니티 조회 기록',
            },
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['views', '-created_at'], name='community_c_views_1be7c4_idx'),
        ),
        migrations.AddField(
            model_name='communitypostlike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='community.communitypost', verbose_name='게시글'),
        ),
        migrations.AddField(
            model_name='communitypostlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_likes', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='communitypostview',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='community.communitypost', verbose_name='게시글'),
        ),
        migrations.AddField(
            model_name='communitypostview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_view_logs', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddIndex(
            model_name='communitypostlike',
            index=models.Index(fields=['post', 'is_active'], name='community_c_post_id_e2fb59_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypostlike',
            index=models.Index(fields=['user', 'is_active'], name='community_c_user_id_c4c86c_idx'),
        ),
        migrations.AddConstraint(
            model_name='communitypostlike',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_community_post_like_per_user'),
        ),
        migrations.AddIndex(
            model_name='communitypostview',
            index=models.Index(fields=['post', 'ip_address'], name='community_c_post_id_f90d1b_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypostview',
            index=models.Index(fields=['created_at'], name='community_c_created_9a5229_idx'),
        ),
        migrations.AddConstraint(
            model_name='communitypostview',
            constraint=models.UniqueConstraint(fields=('post', 'ip_address'), name='unique_community_post_view_per_ip'),
        ),
    ]
