# Generated by Django 6.0.2 on 2026-05-05 00:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_communitypostlike_communitypostview_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitypost',
            options={'ordering': ['-is_notice', '-hot_until', '-bumped_at', '-created_at'], 'verbose_name': '커뮤니티 글', 'verbose_name_plural': '커뮤니티 글'},
        ),
        migrations.AddField(
            model_name='communitypost',
            name='bumped_at',
            field=models.DateTimeField(blank=True, help_text='포인트를 사용해 게시글을 최신 영역으로 끌어올린 시간입니다.', null=True, verbose_name='끌어올린 시간'),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='hot_until',
            field=models.DateTimeField(blank=True, help_text='이 시간까지 핫라인 상위 노출됩니다.', null=True, verbose_name='핫라인 노출 종료'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['hot_until', '-created_at'], name='community_c_hot_unt_aa74ff_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['bumped_at', '-created_at'], name='community_c_bumped__037ff2_idx'),
        ),
    ]
