# Generated by Django 6.0.2 on 2026-05-05 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_communitypost_options_communitypost_bumped_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='bumped_at',
            field=models.DateTimeField(blank=True, help_text='포인트를 사용해 게시글을 최신 영역으로 끌어올린 시간입니다. 별도 표시 효과는 없습니다.', null=True, verbose_name='끌어올린 시간'),
        ),
    ]
