# Generated by Django 6.0.2 on 2026-05-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=20, unique=True, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='recovery_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='보호 이메일'),
        ),
    ]
