# Generated by Django 6.0.2 on 2026-05-04 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_nickname_alter_profile_recovery_email'),
        ('posts', '0016_alter_place_options_alter_post_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '프로필', 'verbose_name_plural': '프로필'},
        ),
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.PositiveIntegerField(default=0, verbose_name='보유 포인트'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.CreateModel(
            name='PointHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='포인트 변동')),
                ('reason', models.CharField(choices=[('route_approved', '루트 승인 보상'), ('route_bonus', '우수 루트 추가 보상'), ('shop_purchase', '포인트샵 사용'), ('admin_adjust', '관리자 조정')], max_length=30, verbose_name='사유')),
                ('memo', models.CharField(blank=True, default='', max_length=255, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_accounts_point_histories', to=settings.AUTH_USER_MODEL, verbose_name='처리자')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_point_histories', to='posts.post', verbose_name='관련 여행 루트')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_point_histories', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '포인트 기록',
                'verbose_name_plural': '포인트 기록',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_po_user_id_765e21_idx'), models.Index(fields=['reason'], name='accounts_po_reason_e94f4c_idx'), models.Index(fields=['post'], name='accounts_po_post_id_18c6d0_idx'), models.Index(fields=['created_at'], name='accounts_po_created_8304bf_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('post__isnull', False), ('reason', 'route_approved')), fields=('reason', 'post'), name='unique_accounts_route_approved_point_per_post')],
            },
        ),
    ]
