# Generated by Django 6.0.2 on 2026-05-04 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_options_profile_points_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pointhistory',
            name='accounts_po_user_id_765e21_idx',
        ),
        migrations.RemoveIndex(
            model_name='pointhistory',
            name='accounts_po_reason_e94f4c_idx',
        ),
        migrations.RemoveIndex(
            model_name='pointhistory',
            name='accounts_po_post_id_18c6d0_idx',
        ),
        migrations.RemoveIndex(
            model_name='pointhistory',
            name='accounts_po_created_8304bf_idx',
        ),
        migrations.RemoveConstraint(
            model_name='pointhistory',
            name='unique_accounts_route_approved_point_per_post',
        ),
        migrations.DeleteModel(
            name='PointHistory',
        ),
    ]
