# Generated by Django 6.0.2 on 2026-05-05 04:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_pointhistory_accounts_po_user_id_765e21_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_earned_points',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='포인트를 사용해도 줄어들지 않는 누적 포인트입니다. 레벨 계산에 사용됩니다.', verbose_name='누적 획득 포인트'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['points'], name='accounts_pr_points_8f5f89_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['total_earned_points'], name='accounts_pr_total_e_0de5e7_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['nickname'], name='accounts_pr_nicknam_3aefb5_idx'),
        ),
    ]
