# Generated by Django 6.0.2 on 2026-05-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_total_earned_points_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='profile',
            name='accounts_pr_nicknam_3aefb5_idx',
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True, verbose_name='닉네임'),
        ),
    ]
