# Generated by Django 6.0.2 on 2026-05-05 01:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='코스 제목')),
                ('summary', models.CharField(blank=True, max_length=180, verbose_name='한 줄 요약')),
                ('total_time', models.CharField(blank=True, max_length=80, verbose_name='예상 소요 시간')),
                ('total_cost', models.CharField(blank=True, max_length=80, verbose_name='예상 비용')),
                ('content', models.TextField(help_text='시간대별 일정, 추천 이유, 이동 팁을 자세히 적어주세요.', verbose_name='상세 코스')),
                ('is_selected', models.BooleanField(default=False, verbose_name='채택 여부')),
                ('is_active', models.BooleanField(default=True, verbose_name='노출 여부')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_answers', to=settings.AUTH_USER_MODEL, verbose_name='답변자')),
            ],
            options={
                'verbose_name': '루트 의뢰 답변',
                'verbose_name_plural': '루트 의뢰 답변',
                'ordering': ['-is_selected', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='의뢰 제목')),
                ('start_area', models.CharField(blank=True, help_text='예: 인천 청라, 서울역, 부산 해운대', max_length=80, verbose_name='출발지')),
                ('destination', models.CharField(help_text='예: 강릉, 제주, 전주', max_length=80, verbose_name='목적지')),
                ('travel_date', models.DateField(blank=True, null=True, verbose_name='여행 예정일')),
                ('people_count', models.PositiveSmallIntegerField(default=2, verbose_name='인원')),
                ('transport', models.CharField(choices=[('any', '상관없음'), ('walk', '뚜벅이'), ('car', '자차'), ('public', '대중교통'), ('rent', '렌트카')], default='any', max_length=20, verbose_name='이동수단')),
                ('budget', models.CharField(blank=True, help_text='예: 총 20만원, 1인 5만원', max_length=80, verbose_name='예산')),
                ('request_detail', models.TextField(help_text='원하는 여행 스타일, 피하고 싶은 장소, 꼭 가고 싶은 곳 등을 적어주세요.', verbose_name='요청 내용')),
                ('reward_points', models.PositiveIntegerField(help_text='답변 채택 시 채택자에게 지급될 포인트입니다.', verbose_name='채택 보상 포인트')),
                ('status', models.CharField(choices=[('open', '모집중'), ('selected', '채택완료'), ('canceled', '취소됨'), ('refunded', '환불됨')], default='open', max_length=20, verbose_name='상태')),
                ('deadline_at', models.DateTimeField(verbose_name='마감 시간')),
                ('selected_at', models.DateTimeField(blank=True, null=True, verbose_name='채택일')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='환불일')),
                ('is_active', models.BooleanField(default=True, verbose_name='노출 여부')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_requests', to=settings.AUTH_USER_MODEL, verbose_name='의뢰자')),
                ('selected_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_for_requests', to='auctions.auctionanswer', verbose_name='채택 답변')),
            ],
            options={
                'verbose_name': '루트 의뢰',
                'verbose_name_plural': '루트 의뢰',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='auctionanswer',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='auctions.auctionrequest', verbose_name='의뢰'),
        ),
        migrations.AddIndex(
            model_name='auctionrequest',
            index=models.Index(fields=['status', '-created_at'], name='auctions_au_status_01a229_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionrequest',
            index=models.Index(fields=['destination', '-created_at'], name='auctions_au_destina_625fcc_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionrequest',
            index=models.Index(fields=['deadline_at'], name='auctions_au_deadlin_5a2370_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionrequest',
            index=models.Index(fields=['reward_points'], name='auctions_au_reward__6702ea_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionanswer',
            index=models.Index(fields=['request', 'is_active', 'created_at'], name='auctions_au_request_a92895_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionanswer',
            index=models.Index(fields=['author', 'created_at'], name='auctions_au_author__5c6704_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionanswer',
            index=models.Index(fields=['is_selected'], name='auctions_au_is_sele_0ab3d1_idx'),
        ),
    ]
